# Data Preprocessing

## Data Preprocessing Techniques: From Raw Data to Machine Learning Datasets
1. Importing the libraries
2. Importing the datasets
3. Taking care of missing data
4. Encoding the categorical data
   - Encoding the Independent Variable
   - Encoding the Dependent Variable
5. Splitting the dataset into the Training set and Test set
6. Feature Scaling

### Step 1: Machine Learning Toolkit: Importing Numpy, Matplotlib, and pandas libraries

In [3]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Step 2: Machine Learning Basics: Importing Datasets using Pandas read_csv()

In [5]:
# Importing the dataset
dataset = pd.read_csv("Data.csv")
# Using pandas iloc for feature selection in ML data preprocessing
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [8]:
# Preprocessing Data: Building X and Y Vectors for ML Model Training
print("""
# ----------------------------------------------------------------- #
# X
# ----------------------------------------------------------------- #
""")
print(X)

print("""
# ----------------------------------------------------------------- #
# y
# ----------------------------------------------------------------- #
""")
print(y)


# ----------------------------------------------------------------- #
# X
# ----------------------------------------------------------------- #

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

# ----------------------------------------------------------------- #
# y
# ----------------------------------------------------------------- #

<ArrowStringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str


### Step 3: Using Scikit-Learn to replace missing values in machine learning 

In [12]:
# Taking care of missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

# Imputing missing data in python: SimpleImputer and Numerical Columns
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Step 4: One-Hot encoding: Transforming categorical features for Machine Learning

#### Encoding the independent variable

In [14]:
# importing required libraries
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [17]:
# Handling Categorical Data: One-hot Encoding with Column Transformer
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder="passthrough")
print(ct.fit_transform(X))

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [18]:
# Preprocessing categorical data: One hot and label encoding Technique
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


#### Encoding the dependent variable

In [20]:
from sklearn.preprocessing import LabelEncoder
lc = LabelEncoder()
y = lc.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


### Step 5: How to prepare Data for Machine Learning: Training and Test Sets

In [21]:
# Splitting the data set into the training set and test set
# Q: do we need to train our dataset before or after feature scaling
# A: After: To prevent information leakage of test set before training is done

# Creating Training and Test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1)

# Splitting data into Training and Test sets: 
print("X train data")
print(X_train)
print("X test data")
print(X_test)
print("y train data")
print(y_train)
print("y test data")
print(y_test)

X train data
[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
X test data
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
y train data
[0 1 0 0 1 1 0 1]
y test data
[0 1]


### Step 6: Feature Scaling in Machine Learning: Why its crucial for Data preprocessing
1. Standardisation
Xstd = (X - mean(X))/std(X)
range = [-3 , 3]
all the time

2. Normalization
Xnorm = (X - min(X))/(max(X) - min(X))
range = [0 , 1]
for normal distribution / specific situation

In [22]:
# How to Scale numeric features for machine learning
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Implementing Feature Scaling: Fit and Transform methods
X_train[:,3:] = sc.fit_transform(X_train[:,3:])

# Applying the same scaler to training and test set
X_test[:, 3:] = sc.transform(X_test[:,3:])
print(X_train)
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
